title: tophackr blog
description: blog of services tophackr
baseurl: ''
url: 'https://blog.tophackr.com'
repository: 'https://gitlab.com/tophackr/blog'
email: tophackr@icloud.com
logo: '/assets/brand.svg'
services:
  - name: Contact
    url: mailto:tophackr@icloud.com
  - name: Anonymous Cloud Storage
    url: https://topdi.sk
  - name: Theme for TeamSpeak 3
    url: https://toptheme.ga
  - name: Status
    url: https://status.tophackr.com

paginate: 1
jekyll-mentions: /u

tag_page_layout: author
tag_page_dir: u

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: /:year-:month-:day/:title/
exclude: [".gitignore", Gemfile, Gemfile.lock, README.md]